### ISSUE TITLE
GBIF ECA nodes meeting in Warsaw May 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#10]
### [GBIF ECA Nodes meeting (ECA2023)](https://www.gbif.org/event/7po0ipGIjX0eXH4lsNzDmH/europe-and-central-asia-nodes-meeting-2023)
Dates: 15-17 (-18) May 2023
Location: Warsaw, Poland
Attendance: Dag and Erik

https://bit.ly/gbif-eca2023

Back-to-bach side-event: [BioDT task 4.3 bioRI national governance models](https://github.com/uio-mana/Events/issues/1) (17-18 May)

**Comment by ErikKusch** [comment]
Workshop was a success. We gained important insight on several RI governance models which GBIF nodes are involved with across Europe. These may be useful to investigate via network analyses of the RI landscapes themselves and link the structure of such networks to DT readiness
