### ISSUE TITLE
Living Norway Open Science course November 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#11]
### Living Norway Open Science course November 2023

Dates: 2023-11-13 to 17
Location: Dovre (to-be-confirmed)
Aud Halbritter UiB is coordinating

We are planning a new Living Norway Open Science course (13-17 Nov) likely at Dovre.
[This is the same course as the BioDATA students attended in Finse last year](https://www.gbif.no/events/2022/open-science-course.html).

It might maybe be sufficient for Michal and Erik (and Dag?) to teach the GBIF/MaNa contributions at this open science course ???

**Comment by ErikKusch** [comment]
I would gladly contribute!

**Comment by dagendresen** [comment]
Great!! Thanks! Very happy you are positive! We can plan more when dates are closer, however, October and November are already starting to fill up incredibly fast. We do need to start planning to avoid too many of us becoming double-booked). (Assuming that the BioDT "bring-your-own-data/research-questions" should be the first priority for you and Desalegn in November).

**Comment by ErikKusch** [comment]
Event has happened and was attended by @dagendresen , @cjandrew , and @ErikKusch.
