### ISSUE TITLE
Marine data publishing workshop Sept 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#13]
### [Marine data publishing workshop](https://www.gbif.no/events/2023/nansen-legacy-oslo.html) together with [Nansen Legacy](https://arvenetternansen.com/) (AeN)

Dates: 2023-09-21 to 22
Location: UiO NHM Tøyen, Oslo
Attendance: (all?), Luke (AeN), Rukaya, Michal, Vidar, Dag, Erik, Andreas (UiT), [Katrine (UiB)?]

Rukaya has booked the venue at Tøyen Manor
TODO: catering etc...

**Comment by ErikKusch** [comment]
Event happened.
