### ISSUE TITLE
MaNa Julebord

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#14]
We are planning a MaNa group social retreat in early autumn 2023

Venue options
* Øvre Heimdalsvatn UiO NHM research station?
* Book a cottage in the Oslo Nordmarka?
* ...?

Timing:
* when?

**Comment by dagendresen** [comment]
Øvre Heimdalsvatn:
> It is fully possible and you are very much encouraged to have your retreat at the field station in Øvre Heimdalen. I should warn you that it is not the most accessible and advanced of field stations (mild understatement), but it is set in a stunning landscape. Getting there takes about 4 hours by car/bus, followed by a 40 min walk to the boat and a 20 minute boat trip to the station. The facilities are rather primitive in the sense that there is no electricity (but some solar panels for lighting), water is taken from the creek/lake and there are outdoor loos. Also, you have to bring all the food and drinks you need, and sleeping bags (but there are beds!). There are openings next week (week 34) and in week 37. If this is interesting, I suggest that we have a chat about it in my office. Cheers, Arild

**Comment by ErikKusch** [comment]
This has been changed to be a MaNa Christmas dinner at restaurant [SudOst](https://www.sudost.no/) on 2023-12-15 from 17:30-19:00.

All MaNa staff are invited:
- @dagendresen 
- @rukayaj 
- @cjandrew 
- @MichalTorma 
- @DesalegnChala 
- @vidarbakken
