### ISSUE TITLE
UiO Digital Scholarship Centre (CSC) Days Jan 2024

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#15]
Workshop from January 8 to 12, 2024. Share your expertise with a workshop in digital tools, data management, programming, visualization, and more. At the UiO University Library at campus Blindern.

[Submit proposals for topics](https://nettskjema.no/a/331850) by September 10, 2023. 

DS Days 2024 is organized by [Digital Scholarship Centre (DSC)](https://www.ub.uio.no/bibliotekene/dsc/) in collaboration with [dScience](https://www.uio.no/dscience/), [CarpentryUiO](https://www.ub.uio.no/english/libraries/dsc/carpentry-uio/), [CodeRefinery](https://www.ub.uio.no/english/courses-events/courses/other/coderefinery/), [USIT](https://www.usit.uio.no/), [Elixir Oslo](https://elixir.no/organization/elixir-uio), [simula](https://www.simula.no/), and the [University of Oslo Library](https://www.ub.uio.no/english/).

**Comment by ErikKusch** [comment]
Link to the event: https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/00-mainpage.html. Signup to individual workshops has to be done on a per-workshop basis.

Should we discuss what workshops each team member might want to attend? This way we could ensure MaNa presence at a variety of workshops. I'll start:
- Jan 8: [Project management for R and Rstudio](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/01-projectmanagement-randrstudio.html)
- Jan 10: [Quarto - Next generation R Markdown](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/11-quarto.html)
- Jan 11: [Programming with Julia](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/13-programming-julia.html)
- Jan 12: [Unlock the power of EOSC: Navigating services for research](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/21-unlocking-eosc.html) & Data visualization - LINK COMING SOON

**Comment by Rindiser** [comment]
Jeg vi delta på "Automatic Text Recognition for Historical Documents"

**Comment by dagendresen** [comment]
I plan to attend:
Jan 08 [Omnipy 1](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/22-omnipy-part1.html) & [2](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/22-omnipy-part2.html)
Jan 09 [Transkribus](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/06-transkribus.html)
Jan 10 [FAIR](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/12-fair-morethenabuzzword.html) & [Digitalarkivet](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/05-historical-data-digitalarchives.html)

**Comment by DesalegnChala** [comment]
I plan to attend:
Jan 08 (full day) - Project management for R and Rstudio 
Jan 10 (full day) - FAIR
I haven't yet decided about the other sessions.

**Comment by dagendresen** [comment]
Completed
