### ISSUE TITLE
UiO Data Managers Network meeting 28 Sept

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#17]
The [UiO Data Managers Network](https://www.ub.uio.no/english/libraries/dsc/data-managers-network/index.html) is hosted by the UiO University Library and organizes network meetings for the data managers across all of UiO to get together, learn from each other, and build social connections. For the autumn of 2023 we (likely) plan network seminars/meetings on **Thursday 28th September 2023** and on Thursday 7th December 2023.

**For the 28/9 meeting**, one suggested topic is using communities in Zenodo (considering maybe exploring creating a UiO Data community). Would @rukayaj or @MichalTorma be willing and available to present the [GBIF Norway community in Zenodo](https://zenodo.org/communities/gbif-norway/)? We could also consider presenting the [BioDT community in Zenodo](https://zenodo.org/communities/biodt/?page=1&size=20) - e.g. @ErikKusch ? Another topic could be data archives (and the CoreTrustSeal certification). Maybe three topics (1) GBIF Norway Zenodo community, (2) DataverseNO and other data archives than Zenodo, (3) CoreTrustSeal.

**Comment by rukayaj** [comment]
Yes I'm available then on the 28 Sept. I'll make some slides and put them here, then everyone can contribute to them if I've missed anything.

**Comment by dagendresen** [comment]
Information web page about the event:
https://www.ub.uio.no/english/courses-events/events/dsc/2023/2023-09-28-dmn-open-archives.html

> Live: I would like some more details for the December event before I publish, please update me on names and titles. It would be nice to start with a brief introduction to what FAIR-DOs are before some examples of usage.

**Comment by rukayaj** [comment]
I made a first draft of a few slides:

https://docs.google.com/presentation/d/1rzTKEgeXiO4TyijckufCvtpYjZr6NVWkakcMsdqvKYg/edit#slide=id.p (this is the slides folder in our shared drive)

I actually am finding it hard to come up with 20 minutes of relevant content, so if anyone has any suggestions for additional things to cover please feel free to add to the slides.

**Comment by dagendresen** [comment]
We could include how we use [Zenodo communities in BioDT](https://zenodo.org/communities/biodt/?page=1&size=20)
However, not sure how much time I have to add slides on this, maybe e.g. @ErikKusch is able to help a little. Also @DesalegnChala has been adding his own content to the BioDT Zenodo community. In a nutshell, we actively use this Zenodo community as part of the milestone reporting - and of course public outreach on project results to researchers.

https://zenodo.org/communities/biodt/

**Comment by rukayaj** [comment]
I meant to come in yesterday and talk to @DesalegnChala about this but I'm still sick so I think I'd better stay home. I'll catch up with everyone on Monday!

**Comment by DesalegnChala** [comment]
@rukayaj - Yes, BioDT shares presentation slides, posters and other materials through Zenodo. We can check through these documents and make some notes to be incorporated into the slides.

**Comment by rukayaj** [comment]
Ok so @DesalegnChala and I decided there isn't much more to be added to the slides I've prepared. I think it's ok if it's a shorter presentation with a bit more time for discussion, so I'm going to leave it like this.

**Comment by rukayaj** [comment]
The 28 Sept meeting happened :)
