### ISSUE TITLE
UiO Data Managers Network meeting 7 Dec

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#18]
The [UiO Data Managers Network](https://www.ub.uio.no/english/libraries/dsc/data-managers-network/index.html) is hosted by the UiO University Library and organizes network meetings for the data managers across all of UiO to get together, learn from each other, and build social connections. For the autumn of 2023 we (likely) plan network seminars/meetings on [Thursday 28th September 2023](https://github.com/uio-mana/Events/issues/17) and on **Thursday 7th December 2023**.

**For the 7/12 meeting**, one suggestion is to explore having the meeting at Tøyen. Maybe in the basement library of the Geological Museum (Brøggers hus) or in the Climate house. And to focus on FDO and similar metadata standards. Maybe @ "Carrie Andrew" is willing and interested to present how we use FDOs in BioDT - maybe invite Sharif (WP5) to present online (or maybe we have funding for inviting him in person). Also considering inviting ELIXIR Norway via BioMedData if they are using FDOs. Maybe three speakers? (1) Sharif, (2) Carrie, and somebody from ELIXIR NO. Other suggested speakers? The goal is for the seminar to be useful for the UiO Data Managers widely across all of the departments and units of the university.

**Comment by cjandrew** [comment]
For the 07-December meeting, yes, that would be great to present something.

**Comment by dagendresen** [comment]
Information web page about the DSC events:
https://www.ub.uio.no/english/courses-events/events/dsc/2023/

> Live: I would like some more details for the December event before I publish, please update me on names and titles. It would be nice to start with a brief introduction to what FAIR-DOs are before some examples of usage.

**Comment by dagendresen** [comment]
@cjandrew do we want to volunteer a talk on FDOs for the 7 Dec meeting? Might be a good opportunity for you to learn the FDOs by presenting them? We could also ask if Sharif is available to contribute online (I believe there is no travel budget at the UiO DSC).

Live (UiO DSC) is also interested in FDOs for software - WP5 is also working on wrapping the actual pDTs as FDOs but I am not sure how far the progress is.

**Comment by cjandrew** [comment]
Yes, sounds like a good idea. I can mention in the meeting, or maybe an email might be better (since it is not applicable to others in WP5)?

**Comment by ErikKusch** [comment]
Meeting has happened and was received well by attendees.
