### ISSUE TITLE
GeoCaSe conference Leiden June 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/Events#7]
Naturalis and the CETAF Earth Science Group invite data managers/data curators from institutions with Earth Science collections to a physical workshop that aims to build capacity in mobilizing data to the Geoscience Collections Access Service (GeoCASe). 

Dates: 26 - 27 June 2023
Venue: Naturalis, [Darwinweg 2, 2333 CR Leiden, Netherlands](https://goo.gl/maps/4Q7NTxcaH1y7b4Am7)

Date/Duration: Two Half-day event, DAY 1: 26th June 2023 (12:30 - 17:30 CEST); DAY 2: 27th (9:00 - 13:00) 
Hosts: Naturalis & CETAF Earth Science Group 
[Preliminary Agenda](https://docs.google.com/document/d/1FhKG-4IKjHn1oERRqb35Lq-s9cNTaLFtesnFE5ntwkU/edit#)
[New GeoCASe Manual (Draft)](https://docs.google.com/document/d/1Xs9BdS-2H1RAZ-4iy_FX9o_NloimSpcl-e3lszRTu3g/edit)
The workshop has limited capacity, 1st come 1st served basis. CETAF and DiSSCo members will be given priority. 

[Info and registration form](https://docs.google.com/forms/d/e/1FAIpQLSdSQLutEpjgmU5zvJj_ZH67bpOMuqb_kqtWn8IopuOvPzqV1Q/viewform)

**Comment by ErikKusch** [comment]
@dagendresen  - this sounds interesting and potentially relevant for BioDT task 4.3. Will you attend? Should I?

**Comment by dagendresen** [comment]
I was primarily thinking that this might maybe be relevant for Ruyaya, Michal, or Vidar - or Eirik - to look at publishing the geological collections at the museum.
I am not planning to attend.
Do you want to attend?

**Comment by ErikKusch** [comment]
I thought it sounded interesting, but if not necessary for me to attend, I will abstain for now. Gotta get some work done outside of meetings and workshops ;-)

**Comment by dagendresen** [comment]
No participation from MaNa
